# Generated by Django 4.2.3 on 2023-07-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_company_owner_alter_company_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ManyToManyField(related_name='companies', to='members.cocategory'),
        ),
    ]
