# Generated by Django 4.2.3 on 2023-07-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_company_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
