# Generated by Django 4.2.3 on 2023-08-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanspec',
            name='value',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='textspec',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
