# Generated by Django 4.2.3 on 2023-08-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_booleanspec_value_alter_textspec_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
